KUMF5H_ASP_2022232/Models/FoodRequest.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;


namespace KUMF5H_ASP_2022232.Models


{
    public class FoodRequest
    {

       
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public string Id { get; set; }

        [Required]
        [StringLength(100)]
            public string Name { get; set; }

                [Required]
             [StringLength(1000)]
            [MinLength(5)]
            public string Description { get; set; }

        [Range(1, int.MaxValue)]
        public int Payment { get; set; }

        [DefaultValue("No")]
        public string Deliveryoptions { get; set; }

        [DefaultValue(false)]
        public bool IsDone { get; set; }

        [DefaultValue(false)]
        public bool InProgress { get; set; }


        [Required]
        public byte[] Picture { get; set; }
        [Required]    
        public string PictureContentType { get; set; }

            [ForeignKey(nameof(FoodUser))]
            public string RequestorId { get; set; }



            [NotMapped]
            public virtual FoodUser Requestor { get; set; }


        [NotMapped]
        public FoodUser Contractor { get; set; }


        [NotMapped]
        [JsonIgnore]
        [ValidateNever]

        public virtual List<Ingredient> Ingridients { get; set; }

        [NotMapped]
            [JsonIgnore]
            [ValidateNever]
            public virtual List<Offer> Offers { get; set; }

            [NotMapped]
            [JsonIgnore]
            [ValidateNever]
            public virtual List<Comment> Comments { get; set; }


            public FoodRequest()
            {
                this.Id = Guid.NewGuid().ToString();
            }
        

    }
}

KUMF5H_ASP_2022232/Models/FoodRequestViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace KUMF5H_ASP_2022232.Models
{
    public class FoodRequestViewModel
    {
        [StringLength(100)]
        public string Name { get; set; }


        [StringLength(1000)]
        [MinLength(5)]
        public string Description { get; set; }



        [DefaultValue(false)]
        public bool IsDone { get; set; }

        [Range(1, int.MaxValue)]
        public int Payment  {get; set; }

        public string Deliveryoptions { get; set; }
    }
}

KUMF5H_ASP_2022232/Controllers/FoodrequestController.cs
using KUMF5H_ASP_2022232.Data;
using KUMF5H_ASP_2022232.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KUMF5H_ASP_2022232.Controllers
{
    public class FoodRequestController : Controller
    {
        private readonly IFoodRequestRepository foodrepository;
        private readonly IOfferRepository offerrepository;
        private readonly IFoodUserRepository foodUserRepository;
        private readonly UserManager<FoodUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public FoodRequestController(IFoodRequestRepository frrepository, IFoodUserRepository foodUserRepository, IOfferRepository offerRepo, UserManager<FoodUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.foodrepository = frrepository;
            this.offerrepository = offerRepo;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.foodUserRepository = foodUserRepository;
        }

        public IActionResult Index()
        {
            return View(this.foodrepository.GetAll().OrderBy(f => f.IsDone));
        }

        public IActionResult Details(string id)
        {
            var food = this.foodrepository.GetOne(id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }



        [HttpGet("Image")]
        public IActionResult GetImage(string id)
        {
            FoodRequest f = this.foodrepository.GetOne(id);
            if (f == null)
            {
                return NotFound();
            }

            return new FileContentResult(f.Picture, f.PictureContentType);
        }



        [HttpPost]
        [Authorize]
        public IActionResult Create(FoodRequestViewModel foodrequest, IFormFile picture)
        {
            if (ModelState.IsValid)
            {
                FoodRequest n = new FoodRequest()
                {
                    Name = foodrequest.Name,
                    Description = foodrequest.Description,
                    RequestorId = userManager.GetUserId(User),
                    Payment = foodrequest.Payment,
                    Deliveryoptions = foodrequest.Deliveryoptions
                };
                using (var stream = picture.OpenReadStream())
                {
                    byte[] buffer = new byte[picture.Length];
                    stream.Read(buffer, 0, (int)picture.Length);
                    n.Picture = buffer;
                    n.PictureContentType = picture.ContentType;
                }

                this.foodrepository.Create(n);
                return RedirectToAction(nameof(Index));
            }
            return View(foodrequest);
        }


        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            var product = this.foodrepository.GetOne(id);
            if (product != null && (product.Requestor.Id == userManager.GetUserId(User) || User.IsInRole("Admin")))
            {
                return View(product);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(string id, FoodRequestViewModel foodrequest)
        {
            if (ModelState.IsValid)
            {
                var old = this.foodrepository.GetOne(id);

                if (old.Requestor.Id != userManager.GetUserId(User) && !User.IsInRole("Admin"))
                    return RedirectToAction(nameof(Index));

                old.Name = foodrequest.Name;
                old.Description = foodrequest.Description;
                old.IsDone = foodrequest.IsDone;
                old.Payment = foodrequest.Payment;
                old.Deliveryoptions = foodrequest.Deliveryoptions;
                this.foodrepository.Update(old);
                return RedirectToAction(nameof(Index));
            }

            return View(foodrequest);
        }

        [Authorize]
        public IActionResult Delete(string id)
        {
            var foodrequest = this.foodrepository.GetOne(id);

            if (foodrequest != null && (foodrequest.Requestor.Id == userManager.GetUserId(User) || User.IsInRole("Admin")))
            {
                this.foodrepository.Delete(foodrequest);
            }

            return RedirectToAction(nameof(Index));


        }

        [Authorize]
        public IActionResult ChooseOffer(string foodId, string offerId)
        {
            var food = this.foodrepository.GetOne(foodId);
            var offer = this.offerrepository.GetOne(offerId);
            var contractor = this.foodUserRepository.GetFooduserById(offer.ContractorId);
            var requestor = this.foodUserRepository.GetFooduserById(userManager.GetUserId(User));


            if (food == null || food.Requestor.Id != userManager.GetUserId(User))
                return RedirectToAction(nameof(Index));

            food.InProgress = true;
            offer.Choosen = true;
            food.Contractor = contractor;



            this.foodrepository.Update(food);
            this.offerrepository.Update(offer);


            return RedirectToAction(nameof(Details), "FoodRequest", new { id = foodId });
        }

        [Authorize]
        public IActionResult SeeAcceptedOffers()
        {
            var foodrequest = this.foodrepository.SeeAcceptedOffers(userManager.GetUserId(User));

            return View(foodrequest);
        }


        [Authorize]
        public IActionResult SeeOtherAcceptedOffers(string id)
        {
            var foodrequest = this.foodrepository.SeeAcceptedOffers(id);

            return View(foodrequest);
        }


        [Authorize]
        public IActionResult CompleteRequest(string foodId)
        {
            var food = this.foodrepository.GetOne(foodId);
            var chosenOffer = food.Offers.FirstOrDefault(o => o.Choosen);
            var requestor = this.foodUserRepository.GetFooduserById(food.RequestorId);
            var contractor = this.foodUserRepository.GetFooduserById(userManager.GetUserId(User));

            if (food == null || chosenOffer.ContractorId != userManager.GetUserId(User))
                return RedirectToAction(nameof(Index));


            contractor.Founds = contractor.Founds + food.Payment;

            requestor.Founds = requestor.Founds - food.Payment;

            food.IsDone = true;
            this.foodrepository.Update(food);

            return RedirectToAction(nameof(Details), "FoodRequest", new { id = foodId });
        }


        [Authorize]
        public IActionResult CancelRequest(string foodId)
        {
            var food = this.foodrepository.GetOne(foodId);
            var chosenOffer = food.Offers.Where(x=>x.Choosen==true).First();

            if (food == null || (food.RequestorId != userManager.GetUserId(User) && chosenOffer.ContractorId != userManager.GetUserId(User)))
                return RedirectToAction(nameof(Index));

            food.IsDone = false;
            food.InProgress = false;
            food.Contractor = null;


            if (chosenOffer != null)
            {
                chosenOffer.Choosen = false;
                this.offerrepository.Update(chosenOffer);
            }

            this.foodrepository.Update(food);

            return RedirectToAction(nameof(Details), "FoodRequest", new { id = foodId });
        }



    }
}

KUMF5H_ASP_2022232/Controllers/OfferController.cs
using KUMF5H_ASP_2022232.Data;
using KUMF5H_ASP_2022232.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;

namespace KUMF5H_ASP_2022232.Controllers
{
    public class OfferController : Controller
    {
        IFoodRequestRepository requestRepo;
        IOfferRepository offerRepo;
        private readonly UserManager<FoodUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public OfferController(IFoodRequestRepository requestRepo, IOfferRepository offerRepo, UserManager<FoodUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.requestRepo = requestRepo;
            this.offerRepo = offerRepo;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create(string requestId)
        {
            var foodrequest = this.requestRepo.GetOne(requestId);

            if (foodrequest != null)
            {
                OfferViewModel vm = new OfferViewModel();
                vm.FoodId = requestId;
                vm.Choosen = false;
                
                return View(vm);
            }
            else
            {
                return RedirectToAction(nameof(FoodRequestController.Index), "FoodRequest");
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(OfferViewModel newOffer)
        {
            FoodRequest f = this.requestRepo.GetOne(newOffer.FoodId);

            if (ModelState.IsValid)
            {
                Offer offer = new Offer()
                {

                    FoodId = newOffer.FoodId,
                    ContractorId = userManager.GetUserId(User)
                };

                this.offerRepo.Create(offer);

                return RedirectToAction(nameof(FoodRequestController.Details), "FoodRequest", new { id = newOffer.FoodId });
            }
            else { return View(newOffer); }
        }


     
    }
}

KUMF5H_ASP_2022232/Views/FoodRequest/Create.cshtml
@model KUMF5H_ASP_2022232.Models.FoodRequestViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create a Requets</h1>

<hr />
<div class="row">
    <div class="col-md-4">

        <form enctype="multipart/form-data" asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Deliveryoptions" class="control-label"></label>
                <input asp-for="Deliveryoptions" class="form-control" />
                <span asp-validation-for="Deliveryoptions" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Payment" class="control-label"></label>
                <input asp-for ="Payment" class="form-control" class="form-control" />
                <span asp-validation-for="Payment" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Picture</label>
                <input type="file" name="picture" class="form-control" required />
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary" role="button" aria-pressed="true">Back</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KUMF5H_ASP_2022232/Views/FoodRequest/Delete.cshtml
@model KUMF5H_ASP_2022232.Models.FoodRequest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Confirm Deletion?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Requestor)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Requestor.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsDone)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>

</div>

KUMF5H_ASP_2022232/Views/FoodRequest/Details.cshtml
@using Microsoft.AspNetCore.Identity
@model KUMF5H_ASP_2022232.Models.FoodRequest
@inject UserManager<FoodUser> UserManager

@{
    ViewData["Title"] = "Details";
    List<Offer> offers = Model.Offers;
    Offer choosen = offers.FirstOrDefault(y=> y.Choosen == true)!;
}


<div class="container">

    <div class="col d-block d-md-none">
        <a href="@Url.Action("GetImage", "Product", new {id=Model.Id})">
            <img class="img-fluid" src="@Url.Action("GetImage", "Product", new {id=Model.Id})" />
        </a>
    </div>

    <div class="row">
        <div class="col-12 col-md-8">

            <h1 class="text-capitalize">
                @if (Model.IsDone)
                {
                    <span class="badge bg-danger">Done</span>
                }
                @Html.DisplayFor(model => model.Name)
            </h1>


            <div class="my-3">

                <blockquote class="blockquote">
                    <footer class="blockquote-footer">
                        <small class="text-muted">
                            Reguested by <cite title="Source Title">@Model.Requestor.FirstName @Model.Requestor.LastName[0].</cite>
                        </small>
                    </footer>
                </blockquote>

                @if (User.Identity.IsAuthenticated && (Model.RequestorId == UserManager.GetUserId(User) || await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "Admin")))
                {
                    <a class="btn" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
                    <a class="btn btn-outline-danger btn-light" asp-action="Delete" asp-route-id="@Model?.Id">Delete</a>
                }

                <hr />

                <div>
                    <span class="fs-6 fw-bold">@Html.DisplayNameFor(model => model.Description)</span>
                    <p>
                        @Model.Description
                    </p>
                </div>

                <div>

                    <span class="fs-6 fw-bold">@Html.DisplayNameFor(model => model.Deliveryoptions)</span>
                    <p>
                        @Model.Deliveryoptions
                    </p>
                </div>

                <div>
                    <span class="fs-6 fw-bold">@Html.DisplayNameFor(model => model.Payment)</span>
                    <p>
                        @Model.Payment
                    </p>
                </div>

            </div>
        </div>

        <div class="col-4 d-none d-md-block">
            <a href="@Url.Action("GetImage", "FoodRequest", new {id=Model.Id})">
                <img class="img-fluid" src="@Url.Action("GetImage", "FoodRequest", new {id=Model.Id})" />
            </a>
        </div>

        @if (!Model.IsDone && !Model.InProgress)
        {
            <div class="mb-4">
                <div class="d-inline-block align-top">
                    @if (Model.RequestorId == UserManager.GetUserId(User))
                    {
                       
                    }
                    else
                    {
                        <a class="btn btn-primary btn-lg" href="@Url.Action("Create", "Offer", new {requestId=Model.Id})">New Offer</a>
                    }
                </div>
               
            </div>
            <div>
                <h4>Offers:</h4>
                <ul>
                    @foreach (var offer in Model.Offers)
                    {
                        var contractor = await UserManager.FindByIdAsync(offer.ContractorId);
                        <li>
                            <a href="@Url.Action("SeeOtherAcceptedOffers", "FoodRequest", new { id = contractor.Id })">@contractor.Email</a>

                            @if (!offer.Choosen && Model.RequestorId == UserManager.GetUserId(User))
                            {
                                <a disabled class="btn btn-success btn-lg" href="@Url.Action("ChooseOffer", "FoodRequest", new { foodId = Model.Id, offerId = offer.Id })">Accept Offer</a>
                            }
                            @if (offer.Choosen && Model.RequestorId == UserManager.GetUserId(User))
                            {
                                <a disabled class="btn btn-success btn-lg" href="@Url.Action("CancelRequest", "FoodRequest", new { foodId = Model.Id })">Cancel Offer</a>
                            }
                        </li>
                    }
                </ul>
            </div>
        }
        else if (Model.InProgress)
        {
            <div class="my-3 fw-bold">
                In Progress
            </div>

            @if (Model.Offers.FirstOrDefault(o => o.Choosen).ContractorId == UserManager.GetUserId(User))
            {
                <div class="mb-4">
                    <div class="d-inline-block align-top">
                        <a class="btn btn-success btn-lg" href="@Url.Action("CompleteRequest", "FoodRequest", new { foodId = Model.Id })">Complete Request</a>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="d-inline-block align-top">
                        <a class="btn btn-danger btn-lg" href="@Url.Action("CancelRequest", "FoodRequest", new { foodId = Model.Id })">Cancel Request</a>
                    </div>
                </div>
            }
            else if (Model.RequestorId == UserManager.GetUserId(User))
            {

                <div class="mb-4">
                    <div class="d-inline-block align-top">
                        <a class="btn btn-danger btn-lg" href="@Url.Action("CancelRequest", "FoodRequest", new { foodId = Model.Id })">Cancel Request</a>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="my-3 fw-bold">
                Done
            </div>

        }
    
    </div>
    <a class="btn btn-secondary" asp-action="Index">< Requests Listt</a>
</div>

KUMF5H_ASP_2022232/Views/FoodRequest/Edit.cshtml
@model KUMF5H_ASP_2022232.Models.FoodRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden" name="SellerId" value="@Model.RequestorId" />
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDone" /> @Html.DisplayNameFor(model => model.IsDone)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KUMF5H_ASP_2022232/Views/FoodRequest/Index.cshtml
@model IEnumerable<KUMF5H_ASP_2022232.Models.FoodRequest>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<FoodUser> SignInManager
@inject UserManager<FoodUser> UserManager

@{
    ViewData["Title"] = "Index";    
    Layout = "_Layout";

}

<div class="text-center">
    <h1 class="display-4">Food For Request</h1>
    <p>Get all the food you need from people you don't know</p>
</div>

<div class="text-right m-4">
    <a class="btn btn-primary btn-lg text-capitalize" asp-action="Create">Request Food!</a>
</div>

<div class="row row-cols-sm-2 row-cols-1 row-cols-lg-4 g-4">

    @foreach (var item in Model)
    {

        string? imgClass = item.IsDone ? "done-img" : null;

        <div class="col">
            <div class="card h-100">

                <img class="card-img-top img-fluid @imgClass" src="@Url.Action("GetImage", "FoodRequest", new {id = item.Id})" alt="@item.Name" />

                <div class="card-body">

                    <h5 class="card-title">
                        @if (item.IsDone)
                        {
                            <span class="badge bg-danger">Done</span>
                        }
                        @Html.DisplayFor(modelItem => item.Name)
                    </h5>

                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>

                    <blockquote class="blockquote mb-0">
                        <footer class="blockquote-footer">
                            <small class="text-muted">
                                Requested by <cite title="Source Title">@item.Requestor.FirstName @item.Requestor.LastName[0].</cite>
                            </small>
                        </footer>
                    </blockquote>

                </div>
                <div class="card-footer">
                    <div class="float-end">
                        <a asp-action="Details" class="stretched-link btn btn-primary" asp-route-id="@item.Id">View Details</a>
                    </div>
                </div>

            </div>
        </div>
    }
</div>

KUMF5H_ASP_2022232/Views/FoodRequest/SeeAcceptedOffers.cshtml
@model IEnumerable<KUMF5H_ASP_2022232.Models.FoodRequest>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<FoodUser> SignInManager
@inject UserManager<FoodUser> UserManager

@{
    ViewData["Title"] = "My Contracts";
}

<div class="text-center">
    <h1 class="display-4">My Contracts</h1>
    <p>View your food contracts.</p>
</div>

@if (!Model.Any())
{
    <p>No Contracts.</p>
}
else
{
    <div class="row row-cols-sm-2 row-cols-1 row-cols-lg-4 g-4">
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card h-100">

                    <img class="card-img-top img-fluid" src="@Url.Action("GetImage", "FoodRequest", new { id = item.Id })" alt="" />
                    <div class="card-body">

                        <h5 class="card-title">
                            @Html.DisplayFor(modelItem => item.Name)
                        </h5>

                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>

                        <blockquote class="blockquote mb-0">
                            <footer class="blockquote-footer">
                                <small class="text-muted">
                                    Sold by <cite title="Source Title">@item.Requestor.FirstName @item.Requestor.LastName[0].</cite>
                                </small>
                            </footer>
                        </blockquote>

                    </div>

                    <div class="card-footer">
                        <div class="float-end">
                            <a asp-action="Details" class="stretched-link btn btn-primary" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
}

KUMF5H_ASP_2022232/Views/FoodRequest/SeeOtherAcceptedOffers.cshtml
@model IEnumerable<KUMF5H_ASP_2022232.Models.FoodRequest>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<FoodUser> SignInManager
@inject UserManager<FoodUser> UserManager

@{
    ViewData["Title"] = "Other Contracts";
}

<div class="text-center">
    <h1 class="display-4"> Contracts</h1>
    <p>View other  food contracts.</p>
</div>

@if (!Model.Any())
{
    <p>No Contracts.</p>
}
else
{
    <div class="row row-cols-sm-2 row-cols-1 row-cols-lg-4 g-4">
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card h-100">

                    <img class="card-img-top img-fluid" src="@Url.Action("GetImage", "FoodRequest", new { id = item.Id })" alt="" />
                    <div class="card-body">

                        <h5 class="card-title">
                            @Html.DisplayFor(modelItem => item.Name)
                        </h5>

                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>

                        <blockquote class="blockquote mb-0">
                            <footer class="blockquote-footer">
                                <small class="text-muted">
                                    Sold by <cite title="Source Title">@item.Requestor.FirstName @item.Requestor.LastName[0].</cite>
                                </small>
                            </footer>
                        </blockquote>

                    </div>

                    <div class="card-footer">
                        <div class="float-end">
                            <a asp-action="Details" class="stretched-link btn btn-primary" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
}